# Generated by Django 5.1.1 on 2024-12-03 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_post_author_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hot',
            field=models.BooleanField(default=False),
        ),
    ]
