# Generated by Django 5.1.1 on 2024-12-03 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
