# Generated by Django 5.1.1 on 2024-12-04 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='post_count',
            field=models.IntegerField(default=0),
        ),
    ]
