# Generated by Django 5.1.1 on 2024-12-04 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_category_post_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='post_count',
        ),
    ]
