# Generated by Django 5.1.1 on 2024-12-05 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_comment_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
